apiVersion: v1
data:
  cilium-policy.yaml: |-
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "default-cluster-policy"
    spec:
      description: "allow cluster intra cluster traffic"
      endpointSelector: {}
      ingress:
        - fromEntities:
            - cluster
        - fromCIDR:
            - 10.0.0.0/8
            - 192.168.128.0/17
    ---
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "default-external-policy"
    spec:
      description: "allow api server traffic"
      nodeSelector: {}
      ingress:
        - fromEntities:
            - cluster
        - fromCIDR:
            - 10.0.0.0/8
        - fromEntities:
            - all
          toPorts:
            - ports:
              - port: "6443"
kind: ConfigMap
metadata:
  name: test-workload-cilium-policy
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: test-workload-credentials
  namespace: default
stringData:
  apiToken: ${LINODE_TOKEN}
  dnsToken: ${LINODE_TOKEN}
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-test-workload-crs-0
  namespace: default
stringData:
  linode-ca.yaml: |-
    kind: Secret
    apiVersion: v1
    metadata:
      name: linode-ca
      namespace: kube-system
    data:
      cacert.pem: ""
  linode-token-region.yaml: |-
    kind: Secret
    apiVersion: v1
    metadata:
      name: linode-token-region
      namespace: kube-system
    stringData:
      apiToken: ${LINODE_TOKEN}
      region: ${LINODE_REGION}
type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: test-workload-cilium
  namespace: default
spec:
  chartName: cilium
  clusterSelector:
    matchLabels:
      cni: test-workload-cilium
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://helm.cilium.io/
  valuesTemplate: |
    bgpControlPlane:
      enabled: true
    routingMode: native
    tunnel: disabled
    kubeProxyReplacement: true
    ipv4NativeRoutingCIDR: 10.0.0.0/8
    egressGateway:
      enabled: true
    enableIPv4Masquerade: true
    enableBFPMasquerade: true
    policyEnforcementMode: "default"
    hostFirewall:
      enabled: true
    extraConfig:
      allow-localhost: policy
    k8sServiceHost: {{ .InfraCluster.spec.controlPlaneEndpoint.host }}
    k8sServicePort: {{ .InfraCluster.spec.controlPlaneEndpoint.port }}
    extraArgs:
    - --nodeport-addresses=0.0.0.0/0
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: false
    k8s:
      requireIPv4PodCIDR: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
  version: 1.19.3
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: test-workload-csi-driver-linode
  namespace: default
spec:
  chartName: linode-blockstorage-csi-driver
  clusterSelector:
    matchLabels:
      csi: test-workload-linode
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://linode.github.io/linode-blockstorage-csi-driver/
  valuesTemplate: |
    secretRef:
      name: "linode-token-region"
      apiTokenRef: "apiToken"
    csiLinodePlugin:
      env:
        - name: LINODE_URL
          value: "https://api.linode.com"
        - name: SSL_CERT_DIR
          value: "/tls"
      volumeMounts:
        - name: cacert
          mountPath: /tls
          readOnly: true
      volumes:
        - name: cacert
          secret:
            secretName: linode-ca
            defaultMode: 420
  version: v1.0.9
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: test-workload-linode-cloud-controller-manager
  namespace: default
spec:
  chartName: ccm-linode
  clusterSelector:
    matchLabels:
      ccm: test-workload-linode
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://linode.github.io/linode-cloud-controller-manager/
  valuesTemplate: |
    routeController:
      vpcNames: {{ .InfraCluster.spec.vpcRef.name }}
      clusterCIDR: 10.0.0.0/8
      configureCloudRoutes: true
    secretRef:
      name: "linode-token-region"
    image:
      pullPolicy: IfNotPresent
    env:
      - name: LINODE_EXTERNAL_SUBNET
        value: ""
      - name: LINODE_URL
        value: "https://api.linode.com"
      - name: SSL_CERT_DIR
        value: "/tls"
      - name: LINODE_API_VERSION
        value: v4beta
    volumeMounts:
      - name: cacert
        mountPath: /tls
        readOnly: true
    volumes:
      - name: cacert
        secret:
          secretName: linode-ca
          defaultMode: 420
  version: v0.9.1
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: test-workload-cilium-policy
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster: test-workload
  resources:
    - kind: ConfigMap
      name: test-workload-cilium-policy
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: test-workload-crs-0
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      crs: test-workload-crs
  resources:
    - kind: Secret
      name: linode-test-workload-crs-0
  strategy: ApplyOnce
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: test-workload
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            - name: cloud-provider
              value: external
          name: "{{ ds.meta_data.label }}"
      preKubeadmCommands:
        - curl -fsSL https://github.com/linode/cluster-api-provider-linode/raw/dd76b1f979696ef22ce093d420cdbd0051a1d725/scripts/pre-kubeadminit.sh
          | bash -s v1.34.2
        - hostnamectl set-hostname '{{ ds.meta_data.label }}' && hostname -F /etc/hostname
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    ccm: test-workload-linode
    cluster: test-workload
    cni: test-workload-cilium
    crs: test-workload-crs
    csi: test-workload-linode
    env: fv
  name: test-workload
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.192.0.0/10
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: test-workload-cp
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: LinodeCluster
    name: test-workload
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: test-workload
  namespace: default
spec:
  clusterName: test-workload
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: test-workload
      clusterName: test-workload
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: LinodeMachineTemplate
        name: test-workload
      version: v1.34.2
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: test-workload-cp
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        extraArgs:
          - name: cloud-provider
            value: external
      etcd:
        local:
          dataDir: /var/lib/etcd_data/etcd
          extraArgs:
            - name: quota-backend-bytes
              value: "8589934592"
    initConfiguration:
      localAPIEndpoint:
        bindPort: 6443
      nodeRegistration:
        kubeletExtraArgs:
          - name: cloud-provider
            value: external
        name: "{{ ds.meta_data.label }}"
      timeouts:
        kubernetesAPICallSeconds: 300
      skipPhases:
        - addon/kube-proxy
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          - name: cloud-provider
            value: external
        name: "{{ ds.meta_data.label }}"
    preKubeadmCommands:
      - curl -fsSL https://github.com/linode/cluster-api-provider-linode/raw/dd76b1f979696ef22ce093d420cdbd0051a1d725/scripts/pre-kubeadminit.sh
        | bash -s v1.34.2
      - hostnamectl set-hostname '{{ ds.meta_data.label }}' && hostname -F /etc/hostname
  machineTemplate:
    metadata:
      labels:
        node-role.kubernetes.io/control-plane: ""
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: LinodeMachineTemplate
        name: test-workload-cp
  replicas: 1
  version: v1.34.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeCluster
metadata:
  name: test-workload
  namespace: default
spec:
  credentialsRef:
    name: test-workload-credentials
  network:
    apiserverLoadBalancerPort: 6443
    subnetName: default
  nodeBalancerFirewallRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: LinodeFirewall
    name: test-workload-nb
  region: ${LINODE_REGION}
  vpcRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: LinodeVPC
    name: test-workload
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeFirewall
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test-workload
  name: test-workload
  namespace: default
spec:
  credentialsRef:
    name: test-workload-credentials
  enabled: false
  inboundPolicy: DROP
  inboundRules:
    - action: ACCEPT
      addresses:
        ipv4:
          - 10.0.0.0/8
      description: accept all tcp traffic within the vpc
      label: intra-cluster-tcp
      ports: 1-65535
      protocol: TCP
    - action: ACCEPT
      addresses:
        ipv4:
          - 10.0.0.0/8
      description: accept all udp traffic within the vpc
      label: intra-cluster-udp
      ports: 1-65535
      protocol: UDP
    - action: ACCEPT
      addresses:
        ipv4:
          - 10.0.0.0/8
      description: accept all icmp traffic within the vpc
      label: intra-cluster-icmp
      protocol: ICMP
    - action: ACCEPT
      addresses:
        ipv4:
          - 192.168.255.0/24
      description: accept all api server related traffic from nodebalancers
      label: inbound-api-server
      ports: "6443"
      protocol: TCP
    - action: ACCEPT
      addresses:
        ipv4:
          - 192.168.255.0/24
      description:
        accept traffic from the entire NodeBalancer CIDR to the NodePort
        service range
      label: accept-NodeBalancer
      ports: 30000-32767
      protocol: TCP
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeFirewall
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test-workload
  name: test-workload-nb
  namespace: default
spec:
  credentialsRef:
    name: test-workload-credentials
  enabled: false
  inboundPolicy: DROP
  inboundRules:
    - action: ACCEPT
      addresses:
        ipv4:
          - 0.0.0.0/0
        ipv6:
          - ::/0
      description: accept all api server related traffic from nodebalancers
      label: inbound-api-server
      ports: "6443"
      protocol: TCP
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: test-workload
  namespace: default
spec:
  template:
    spec:
      authorizedKeys:
        - "${PUBLIC_SSH_KEY}"
      firewallRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeFirewall
        name: test-workload
      image: linode/ubuntu22.04
      interfaces:
        - purpose: public
      region: ${LINODE_REGION}
      type: ${LINODE_MACHINE_TYPE}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: test-workload-cp
  namespace: default
spec:
  template:
    spec:
      authorizedKeys:
        - "${PUBLIC_SSH_KEY}"
      firewallRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeFirewall
        name: test-workload
      image: linode/ubuntu22.04
      interfaces:
        - purpose: public
      region: ${LINODE_REGION}
      type: ${LINODE_CONTROL_PLANE_MACHINE_TYPE}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeVPC
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test-workload
  name: test-workload
  namespace: default
spec:
  credentialsRef:
    name: test-workload-credentials
  region: ${LINODE_REGION}
  subnets:
    - ipv4: 10.0.0.0/8
      label: default
