apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - cluster-proxy-cert.yaml
  - mca-msa.yaml
  - mca-cluster-proxy.yaml

helmCharts:
  - name: cluster-proxy
    includeCRDs: true
    releaseName: cluster-proxy
    version: 0.10.0
    namespace: open-cluster-management-addon
    repo: https://open-cluster-management.io/helm-charts
    valuesInline:
      enableServiceProxy: true
  - name: managed-serviceaccount
    includeCRDs: true
    releaseName: managed-serviceaccount
    version: 0.10.0
    namespace: open-cluster-management-addon
    repo: https://open-cluster-management.io/helm-charts
    valuesInline:
      agentInstallAll: false
