apiVersion: v1
kind: Namespace
metadata:
  name: caaph-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: AddonProvider
metadata:
  name: helm
  namespace: caaph-system
spec:
  version: v0.6.0
