apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/guilhem/sveltos-ocm-addon.git/config/default/
  - configuration.yaml

images:
  - name: controller
    newName: ghcr.io/guilhem/sveltos-ocm-addon
    newTag: main

namespace: sveltos-ocm-addon-system